# Generated by Django 4.2 on 2023-04-12 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование объекта')),
                ('status', models.CharField(choices=[('BR', 'Убитая'), ('WT', 'В ожидании ремонта'), ('PR', 'В процессе ремонта'), ('FD', 'Отремонтирована')], default='FD', max_length=2, verbose_name='Статус объекта')),
                ('geolocation', models.URLField()),
                ('contractor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Подрядчик')),
                ('warranty', models.DurationField(blank=True, null=True, verbose_name='Гарантийный срок')),
                ('repair_date', models.DurationField(blank=True, null=True, verbose_name='Дата ремонта')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст идеи')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обращения')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст жалобы')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_api.road', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('comment', models.TextField(max_length=5000, verbose_name='Комментарий')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_api.road', verbose_name='Объект')),
            ],
        ),
    ]
