# Generated by Django 4.2 on 2023-04-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Населённый пункт')),
            ],
        ),
        migrations.AlterField(
            model_name='road',
            name='status',
            field=models.CharField(choices=[('BR', 'Broken'), ('WT', 'Waiting'), ('PR', 'Process'), ('FD', 'Finished')], max_length=512),
        ),
        migrations.AddField(
            model_name='road',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot_api.city', verbose_name='Населённый пункт'),
            preserve_default=False,
        ),
    ]
