# Generated by Django 4.2 on 2023-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_api', '0005_alter_road_repair_date_alter_road_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='phone',
            field=models.CharField(default='-', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='report',
            name='phone',
            field=models.CharField(default='-', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='phone',
            field=models.CharField(default='-', max_length=15, verbose_name='Телефон'),
        ),
    ]
